### ISSUE TITLE
ActionView::Template::Error happened in UsersController#home

### ISSUE THREAD

**Issue by geotho** [geotho/Peterhouse-May-Ball#3]
**Message**

```
  undefined method `charges' for nil:NilClass
```

**Backtrace (last 10 lines)**

```
app/views/users/home.html.haml:3:in `_app_views_users_home_html_haml__3471722416332993100_69967345607680'
vendor/bundle/ruby/2.0.0/gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
vendor/bundle/ruby/2.0.0/gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
vendor/bundle/ruby/2.0.0/gems/actionview-4.1.6/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
vendor/bundle/ruby/2.0.0/gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
```

View on AppSignal: https://appsignal.com/peterhouse-may-ball/sites/54c7d3d9776f7201f25ba314/web/exceptions/UsersController-hash-home/ActionView::Template::Error

**Comment by geotho** [comment]
Caused by not checking for an existing user on User Controller actions. Specifically User#Home
